### ISSUE TITLE
Difference to `nakedret`?

### ISSUE THREAD

**Issue by scop** [firefart/nonamedreturns#3]
This linter seems similar to https://github.com/alexkohler/nakedret that has existed and been included in golangci-lint for a while, only without the configurability. I suppose configuring `nakedret` with max function length 0 would be pretty much the same as this one.

Am I missing something, and/or are there other more substantial differences between the two?

**Comment by firefart** [comment]
this linter simply checks the function signatures for named returns. nakedret checks for returns without specifying values
